<a href="https://colab.research.google.com/github/kalra-nitish/NLP/blob/main/TextRank_Text_Summarization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd
import numpy as np
import textwrap
import nltk
from nltk.corpus import stopwords
from nltk import word_tokenize
from nltk.stem import WordNetLemmatizer, PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [4]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [5]:
!wget -nc https://lazyprogrammer.me/course_files/nlp/bbc_text_cls.csv

--2024-07-16 18:26:55--  https://lazyprogrammer.me/course_files/nlp/bbc_text_cls.csv
Resolving lazyprogrammer.me (lazyprogrammer.me)... 172.67.213.166, 104.21.23.210, 2606:4700:3031::6815:17d2, ...
Connecting to lazyprogrammer.me (lazyprogrammer.me)|172.67.213.166|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5085081 (4.8M) [text/csv]
Saving to: ‘bbc_text_cls.csv’

bbc_text_cls.csv    100%[===================>]   4.85M  17.3MB/s    in 0.3s    

2024-07-16 18:26:56 (17.3 MB/s) - ‘bbc_text_cls.csv’ saved [5085081/5085081]



In [6]:
df = pd.read_csv('bbc_text_cls.csv')

In [7]:
df.head()

text    labels
0  Ad sales boost Time Warner profit\n\nQuarterly...  business
1  Dollar gains on Greenspan speech\n\nThe dollar...  business
2  Yukos unit buyer faces loan claim\n\nThe owner...  business
3  High fuel prices hit BA's profits\n\nBritish A...  business
4  Pernod takeover talk lifts Domecq\n\nShares in...  business

In [8]:
doc = df[df.labels == 'business']['text'].sample(random_state=42)

In [9]:
doc

480    Christmas sales worst since 1981\n\nUK retail ...
Name: text, dtype: object

In [10]:
def wrap(x):
  return textwrap.fill(x, replace_whitespace=False, fix_sentence_endings=True)

In [11]:

print(wrap(doc.iloc[0]))

Christmas sales worst since 1981

UK retail sales fell in December,
failing to meet expectations and making it by some counts the worst
Christmas since 1981.

Retail sales dropped by 1% on the month in
December, after a 0.6% rise in November, the Office for National
Statistics (ONS) said.  The ONS revised the annual 2004 rate of growth
down from the 5.9% estimated in November to 3.2%. A number of
retailers have already reported poor figures for December.  Clothing
retailers and non-specialist stores were the worst hit with only
internet retailers showing any significant growth, according to the
ONS.

The last time retailers endured a tougher Christmas was 23 years
previously, when sales plunged 1.7%.

The ONS echoed an earlier
caution from Bank of England governor Mervyn King not to read too much
into the poor December figures.  Some analysts put a positive gloss on
the figures, pointing out that the non-seasonally-adjusted figures
showed a performance comparable with 2003. The Novembe

In [12]:
sents = nltk.sent_tokenize(doc.iloc[0].split("\n", 1)[1])

In [13]:
sents

['\nUK retail sales fell in December, failing to meet expectations and making it by some counts the worst Christmas since 1981.',
 'Retail sales dropped by 1% on the month in December, after a 0.6% rise in November, the Office for National Statistics (ONS) said.',
 'The ONS revised the annual 2004 rate of growth down from the 5.9% estimated in November to 3.2%.',
 'A number of retailers have already reported poor figures for December.',
 'Clothing retailers and non-specialist stores were the worst hit with only internet retailers showing any significant growth, according to the ONS.',
 'The last time retailers endured a tougher Christmas was 23 years previously, when sales plunged 1.7%.',
 'The ONS echoed an earlier caution from Bank of England governor Mervyn King not to read too much into the poor December figures.',
 'Some analysts put a positive gloss on the figures, pointing out that the non-seasonally-adjusted figures showed a performance comparable with 2003.',
 'The November-De

In [14]:
featurizer = TfidfVectorizer(stop_words=stopwords.words('english'), norm='l1',)

In [15]:
X = featurizer.fit_transform(sents)

In [18]:
#compute similarity matrix
S = cosine_similarity(X)

In [19]:
S.shape

(17, 17)

In [20]:
len(sents)

17

In [21]:
#normalize similarity matrix
S /= S.sum(axis=1, keepdims=True)

In [22]:
S[0].sum()

1.0

In [23]:
#uniform transition matrix
U = np.ones_like(S) / len(S)

In [24]:
U[0].sum()

1.0

In [25]:
#smoothed similarity matrix
factor = 0.15
S = (1 - factor) * S + factor * U

In [26]:
S[0].sum()

1.0

In [27]:
#find the limiting / stationary distribution
eigenvals, eigenvecs = np.linalg.eig(S.T)

In [28]:
eigenvals

array([1.        , 0.24245466, 0.72108199, 0.67644122, 0.34790129,
       0.34417302, 0.3866884 , 0.40333562, 0.41608572, 0.44238593,
       0.63909999, 0.62556792, 0.58922572, 0.57452382, 0.48511399,
       0.51329157, 0.52975372])

In [30]:
eigenvecs[:, 0]

array([-0.24206557, -0.27051337, -0.2213806 , -0.28613638, -0.25065894,
       -0.2499217 , -0.279622  , -0.21515455, -0.2226665 , -0.22745415,
       -0.2059112 , -0.20959727, -0.23526242, -0.24203809, -0.23663025,
       -0.2940483 , -0.20865607])

In [31]:
eigenvecs[:,0].dot(S)

array([-0.24206557, -0.27051337, -0.2213806 , -0.28613638, -0.25065894,
       -0.2499217 , -0.279622  , -0.21515455, -0.2226665 , -0.22745415,
       -0.2059112 , -0.20959727, -0.23526242, -0.24203809, -0.23663025,
       -0.2940483 , -0.20865607])

In [32]:
eigenvecs[:,0] / eigenvecs[:,0].sum()

array([0.05907327, 0.06601563, 0.05402535, 0.06982824, 0.06117038,
       0.06099047, 0.06823848, 0.05250595, 0.05433915, 0.05550753,
       0.05025022, 0.05114976, 0.05741304, 0.05906657, 0.05774684,
       0.07175905, 0.05092007])

In [35]:
limiting_dist = np.ones(len(S)) / len(S)
threshold = 1e-8
delta = float('inf')
iters = 0
while delta > threshold:
  iters += 1
  #Markov transition
  p = limiting_dist.dot(S)
  #compute change in limiting distribution
  delta = np.abs(p - limiting_dist).sum()
  #update limiting distribution
  limiting_dist = p
  print(iters)


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41


In [36]:
limiting_dist

array([0.05907327, 0.06601563, 0.05402534, 0.06982824, 0.06117038,
       0.06099047, 0.06823848, 0.05250595, 0.05433915, 0.05550753,
       0.05025022, 0.05114977, 0.05741304, 0.05906657, 0.05774685,
       0.07175905, 0.05092008])

In [37]:
limiting_dist.sum()

0.9999999999999982

In [38]:
np.abs(eigenvecs[:,0] / eigenvecs[:,0].sum() - limiting_dist).sum()

1.9964738834366003e-08

In [39]:
scores = limiting_dist

In [40]:
scores

array([0.05907327, 0.06601563, 0.05402534, 0.06982824, 0.06117038,
       0.06099047, 0.06823848, 0.05250595, 0.05433915, 0.05550753,
       0.05025022, 0.05114977, 0.05741304, 0.05906657, 0.05774685,
       0.07175905, 0.05092008])

In [41]:
sort_idx = np.argsort(-scores)

In [42]:
sort_idx

array([15,  3,  6,  1,  4,  5,  0, 13, 14, 12,  9,  8,  2,  7, 11, 16, 10])

In [ ]:
def get_sentence_score(tfidf_row):
  #return the average of the non-zero values
  # of the yf-idf vector representation of a sentence
  x = tfidf_row[tfidf_row != 0 ]
  return x.mean()

In [ ]:
scores = np.zeros(len(sents))
for i in range(len(sents)):
  score = get_sentence_score(X[i, :])
  scores[i] = score

In [ ]:
sort_idx = np.argsort(-scores)

In [ ]:
sort_idx

array([ 3, 10,  2, 16, 12,  5,  1, 11,  4,  7,  6, 14,  0,  9, 13,  8, 15])

In [43]:
print("generated summary:")
for i in sort_idx[:5]:
  print(wrap("%.2f: %s" % (scores[i], sents[i])))

generated summary:
0.07: "The retail sales figures are very weak, but as Bank of England
governor Mervyn King indicated last night, you don't really get an
accurate impression of Christmas trading until about Easter," said Mr
Shaw.
0.07: A number of retailers have already reported poor figures for
December.
0.07: The ONS echoed an earlier caution from Bank of England governor
Mervyn King not to read too much into the poor December figures.
0.07: Retail sales dropped by 1% on the month in December, after a
0.6% rise in November, the Office for National Statistics (ONS) said.
0.06: Clothing retailers and non-specialist stores were the worst hit
with only internet retailers showing any significant growth, according
to the ONS.


In [44]:
doc.iloc[0].split("\n", 1)[0]

'Christmas sales worst since 1981'

In [48]:
def summarize(text):
  #extract sentences
  sents = nltk.sent_tokenize(text)
  #perform tf-idf
  featurizer = TfidfVectorizer(stop_words=stopwords.words('english'), norm = 'l1')
  X = featurizer.fit_transform(sents)
  #compute similarity matrix
  S = cosine_similarity(X)

  #normalize similarity matrix
  S /= S.sum(axis=1, keepdims=True)

  #uniform transition matrix
  U = np.ones_like(S) / len(S)

  #smoothed similarity matrix
  factor = 0.15
  S = (1 - factor) * S + factor * U

  #find the limiting / stationary distribution
  eigenvals, eigenvecs = np.linalg.eig(S.T)

  #compute scores
  scores = eigenvecs[:,0] / eigenvecs[:,0].sum()
  #sort by score
  sort_idx = np.argsort(-scores)
  #print top 5 sentences
  for i in sort_idx[:5]:
    print(wrap("%.2f: %s" % (scores[i], sents[i])))


In [49]:
doc = df[df.labels == "entertainment"]["text"].sample(random_state=123)
summarize(doc.iloc[0].split("\n", 1)[1])

0.11: Goodrem, Green Day and the Black Eyed Peas took home two awards
each.
0.10: As well as best female, Goodrem also took home the Pepsi Viewers
Choice Award, whilst Green Day bagged the prize for best rock video
for American Idiot.
0.10: Other winners included Green Day, voted best group, and the
Black Eyed Peas.
0.10: The Black Eyed Peas won awards for best R 'n' B video and
sexiest video, both for Hey Mama.
0.10: Local singer and songwriter Missy Higgins took the title of
breakthrough artist of the year, with Australian Idol winner Guy
Sebastian taking the honours for best pop video.


In [50]:
doc.iloc[0].split("\n")[0]

'Goodrem wins top female MTV prize'

In [51]:
print(wrap(doc.iloc[0]))

Goodrem wins top female MTV prize

Pop singer Delta Goodrem has
scooped one of the top individual prizes at the first Australian MTV
Music Awards.

The 21-year-old singer won the award for best female
artist, with Australian Idol runner-up Shannon Noll taking the title
of best male at the ceremony.  Goodrem, known in both Britain and
Australia for her role as Nina Tucker in TV soap Neighbours, also
performed a duet with boyfriend Brian McFadden.  Other winners
included Green Day, voted best group, and the Black Eyed Peas.
Goodrem, Green Day and the Black Eyed Peas took home two awards each.
As well as best female, Goodrem also took home the Pepsi Viewers
Choice Award, whilst Green Day bagged the prize for best rock video
for American Idiot.  The Black Eyed Peas won awards for best R 'n' B
video and sexiest video, both for Hey Mama.  Local singer and
songwriter Missy Higgins took the title of breakthrough artist of the
year, with Australian Idol winner Guy Sebastian taking the honours f